/**
 * JobSite API.
 * this api has three main resources jobs, contacts and applicants
 *
 * OpenAPI spec version: 0.0.1
 * Contact: seancarlin90@googlemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ApplicantDto { 
    /**
     * The datetime the applicant applied for the job
     */
    appliedDate?: Date;
    /**
     * The contact id associated with the application
     */
    contactId?: number;
    /**
     * The date time the applicant was first created
     */
    createdtime?: Date;
    /**
     * The applicant id (auto generated)
     */
    id?: number;
    /**
     * The job id associated with the application
     */
    jobId: number;
    /**
     * The date time the applicant record was last modified
     */
    modifiedtime?: Date;
}
